BeginPackage["LSPServer`Socket`"]



findMessageParts
lspMsgAssoc
writeLSPResult

Begin["`Private`"]

Needs["LSPServer`"]
Needs["LSPServer`Utils`"]
Needs["LSPServer`Library`"]
Needs["CodeParser`Utils`"]

(* ========================================================== *)
(* ================   Socket functions   ==================== *)
(* ========================================================== *)

lspMsgAssoc = <|"lspMsg" -> "", "lspMsgs" -> {}, "msgInQueue" -> ""|>

(* =================   Initialize   ======================= *)

(* "tcp_mode": "host", "tcp_port": 5555 *)

initializeLSPComm["Socket"] := SocketConnect[5555, "TCP"]

(* ===============   Message validity check    =============== *)

checkContent[str_] := StringContainsQ[str, "Content-Length: "]

checkStartPosition[str_] := StringStartsQ[str, "Content"]

contentLengthFromHeader[header_String] :=
	Module[{lengths},
		lengths =
			StringCases[
				header,
				"Content-Length:" ~~
				WhitespaceCharacter.. ~~
				length:DigitCharacter.. :> length
			];
		If[lengths === {}, Missing["NotFound"], FromDigits[First[lengths]]]
	]

parseCompleteMessageBodies[buffer_String] :=
	Module[
		{
			remaining = buffer,
			separator = "\r\n\r\n",
			headerPosition,
			header,
			msgLength,
			bodyStart,
			available,
			reaped
		},
		reaped =
			Reap[
				While[
					True,
					headerPosition = StringPosition[remaining, separator, 1];
					If[headerPosition === {}, Break[]];
					header = StringTake[remaining, First[headerPosition][[1]] - 1];
					msgLength = contentLengthFromHeader[header];
					If[!IntegerQ[msgLength] || msgLength < 0, Break[]];
					bodyStart = First[headerPosition][[2]] + 1;
					available = StringLength[remaining] - bodyStart + 1;
					If[available < msgLength, Break[]];
					Sow[
						If[msgLength == 0,
							"",
							StringTake[
								remaining,
								{bodyStart, bodyStart + msgLength - 1}
							]
						]
					];
					remaining =
						StringDrop[remaining, bodyStart + msgLength - 1]
				]
			][[2]];
		{If[reaped === {}, {}, First[reaped]], remaining}
	]

checkMsgLength[str_] := msgContainsQ[str]

msgContainsQ[str_] := First[parseCompleteMessageBodies[str]] =!= {}

findMessageParts[str_String] :=
	Module[{msgBodies, remaining},
		{msgBodies, remaining} =
			parseCompleteMessageBodies[
				StringJoin[Lookup[lspMsgAssoc, "msgInQueue", ""], str]
			];
		lspMsgAssoc["lspMsgs"] = msgBodies;
		lspMsgAssoc["lspMsg"] = If[msgBodies === {}, "", First[msgBodies]];
		lspMsgAssoc["msgInQueue"] = remaining;
		lspMsgAssoc
	]

readParsedMessages[] :=
	Module[{msgBodies, contents},
		msgBodies = Lookup[lspMsgAssoc, "lspMsgs", {}];
		If[msgBodies === {},
			{},
			contents = Developer`ReadRawJSONString /@ msgBodies;
			lspMsgAssoc["lspMsgs"] = {};
			lspMsgAssoc["lspMsg"] = "";
			contents
		]
	]

socketInputReadyQ[sockObj_] :=
	TrueQ[Quiet[Check[SocketReadyQ[sockObj, 0], False]]]




(* ===================     Read     ========================= *)

queueEmptyQ["Socket"] :=
Module[{getMethods},
  getMethods = #["method"]& /@ LSPServer`$ContentQueue;
  MatchQ[getMethods, {}]
]

readMessage["Socket", sockObj_] :=
	Module[{sockMessage, contentsIn},
		contentsIn = readParsedMessages[];
		If[contentsIn =!= {},
			Return[contentsIn]
		];
		If[!socketInputReadyQ[sockObj],
			Return[{}]
		];
		If[contentsIn === {},
			While[
				contentsIn === {} && socketInputReadyQ[sockObj],
				sockMessage = SocketReadMessage[sockObj];
				If[FailureQ[sockMessage],
					log[0, "Read failure from client.\n"];
					exitHard[]
				];
				findMessageParts[ByteArrayToString[sockMessage]];
				contentsIn = readParsedMessages[];
			];
		];
		contentsIn
	]

(* Read + Expand + Update *)

TryQueue["Socket", sockObj_] :=
Catch[
Module[{contentsIn},
  If[queueEmptyQ["Socket"],
    log[2, "\n\n $ContentQueue is empty, No more messages to deliver, Go to Read messages Section.\n\n "];
    ,
    log[2, "\n\n $ContentQueue is not empty, No Read messages.\n\n "];
    Throw[Null]
  ];
  contentsIn = readMessage["Socket", sockObj];
  expandContentsAndAppendToContentQueue[contentsIn];
  Null
]
]




(* ===================     Write     ======================== *)


writeSocket["Socket", socket_, header_, body_] :=
Module[{headerWrite, bodyWrite},

  headerWrite = BinaryWrite[socket, StringToByteArray @ header];

  If[
    FailureQ[headerWrite],
    log[0, "Message-header write failure to client."];
    exitHard[]
  ];

  bodyWrite = BinaryWrite[socket, body];

  If[
    FailureQ[bodyWrite],
    log[0, "Message-body write failure to client."];
    exitHard[]
  ]
]

(* contents is a list of Associations *)
writeLSPResult["Socket", sockObject_, contents_] :=
	Module[{json, bytes, line},
		(*
		Write each response as soon as it is serialized so large batches do not
		hold both all JSON strings and all byte arrays at once.
		*)
		Do[
			json =
				Check[
					Developer`WriteRawJSONString[content],
					log[2, "\n\n"];
					log[2, "message generated by content: ", content];
					log[2, "\n\n"];
					exitHard[],
					{Export::jsonstrictencoding}
				];
			If[FailureQ[json],
				log[0, "\n\n"];
				log[0, "Could not convert to JSON: ", content];
				log[0, "\n\n"];
				exitHard[]
			];
			bytes = StringToByteArray[json];
			If[!ByteArrayQ[bytes],
				log[0, "\n\n"];
				log[0, "invalid bytes: ", bytes];
				log[0, "\n\n"];
				exitHard[]
			];
			line = "Content-Length: " <> ToString[Length[bytes]] <> "\r\n\r\n";
			writeSocket["Socket", sockObject, line, bytes],
			{content, contents}
		]
	]


  (* ================= Read Write Loop =============================== *)
readEvalWriteLoop["Socket", sock_]:=
Module[{content, contents},

  (* Install yield-point thunks so long-running handlers can serve
     interactive requests mid-computation. *)
  LSPServer`$TryQueueThunk = Function[TryQueue["Socket", sock]];
  LSPServer`$WriteLSPResultThunk = Function[{c}, writeLSPResult["Socket", sock, c]];

  While[True,

    TryQueue["Socket", sock];

    ProcessScheduledJobs[];

    If[LSPServer`Private`contentQueueEmptyQ[],
      Pause[LSPServer`$IdleLoopPause];
      Continue[]
    ];

    content = LSPServer`Private`takeFirstContentQueueItem[];

      log[2, "taking first from $ContentQueue: ", #["method"]&[content]];
      log[2, "rest of $ContentQueue (up to 20): ", Take[#["method"]& /@ LSPServer`$ContentQueue, UpTo[20]]];
      log[2, "..."];

    contents = LSPEvaluate[content];

    (* write out evaluated results to the client *)
    writeLSPResult["Socket", sock, contents];

  ](*While*)
]

(* ============================ ShutDown ============================= *)
shutdownLSPComm["Socket", s_SocketObject] := Close[s]

shutdownLSPComm["Socket", _] := Null

End[]

EndPackage[]
